class CountryCode {
  final String flag;
  final String name;
  final String dial;
  const CountryCode(this.flag, this.name, this.dial);

  @override
  bool operator ==(Object other) =>
      other is CountryCode && other.dial == dial && other.name == name;

  @override
  int get hashCode => Object.hash(dial, name);
}

const List<CountryCode> kCountryCodes = [
  // ─── أبرز الدول (أول القائمة) ──────────────────────────────────────────────
  CountryCode('🇩🇪', 'ألمانيا', '+49'),
  CountryCode('🇮🇶', 'العراق', '+964'),
  CountryCode('🇸🇦', 'السعودية', '+966'),
  CountryCode('🇸🇾', 'سوريا', '+963'),
  CountryCode('🇦🇪', 'الإمارات', '+971'),
  CountryCode('🇯🇴', 'الأردن', '+962'),
  CountryCode('🇱🇧', 'لبنان', '+961'),
  CountryCode('🇲🇦', 'المغرب', '+212'),
  CountryCode('🇪🇬', 'مصر', '+20'),
  CountryCode('🇹🇳', 'تونس', '+216'),
  CountryCode('🇩🇿', 'الجزائر', '+213'),
  CountryCode('🇱🇾', 'ليبيا', '+218'),
  CountryCode('🇾🇪', 'اليمن', '+967'),
  CountryCode('🇴🇲', 'عُمان', '+968'),
  CountryCode('🇰🇼', 'الكويت', '+965'),
  CountryCode('🇧🇭', 'البحرين', '+973'),
  CountryCode('🇶🇦', 'قطر', '+974'),
  CountryCode('🇵🇸', 'فلسطين', '+970'),
  CountryCode('🇸🇩', 'السودان', '+249'),
  CountryCode('🇸🇴', 'الصومال', '+252'),
  CountryCode('🇹🇷', 'تركيا', '+90'),
  CountryCode('🇦🇹', 'النمسا', '+43'),
  CountryCode('🇨🇭', 'سويسرا', '+41'),
  CountryCode('🇳🇱', 'هولندا', '+31'),
  CountryCode('🇧🇪', 'بلجيكا', '+32'),
  CountryCode('🇸🇪', 'السويد', '+46'),
  CountryCode('🇳🇴', 'النرويج', '+47'),
  CountryCode('🇩🇰', 'الدنمارك', '+45'),
  CountryCode('🇫🇮', 'فنلندا', '+358'),
  CountryCode('🇬🇧', 'المملكة المتحدة', '+44'),
  CountryCode('🇫🇷', 'فرنسا', '+33'),
  CountryCode('🇮🇹', 'إيطاليا', '+39'),
  CountryCode('🇪🇸', 'إسبانيا', '+34'),
  CountryCode('🇵🇹', 'البرتغال', '+351'),
  CountryCode('🇬🇷', 'اليونان', '+30'),
  CountryCode('🇵🇱', 'بولندا', '+48'),
  CountryCode('🇷🇺', 'روسيا', '+7'),
  CountryCode('🇺🇦', 'أوكرانيا', '+380'),
  CountryCode('🇺🇸', 'الولايات المتحدة', '+1'),
  CountryCode('🇨🇦', 'كندا', '+1'),
  CountryCode('🇦🇺', 'أستراليا', '+61'),
  CountryCode('🇳🇿', 'نيوزيلندا', '+64'),
  CountryCode('🇮🇳', 'الهند', '+91'),
  CountryCode('🇵🇰', 'باكستان', '+92'),
  CountryCode('🇧🇩', 'بنغلاديش', '+880'),
  CountryCode('🇨🇳', 'الصين', '+86'),
  CountryCode('🇯🇵', 'اليابان', '+81'),
  CountryCode('🇰🇷', 'كوريا الجنوبية', '+82'),
  CountryCode('🇮🇩', 'إندونيسيا', '+62'),
  CountryCode('🇵🇭', 'الفلبين', '+63'),
  CountryCode('🇲🇾', 'ماليزيا', '+60'),
  CountryCode('🇸🇬', 'سنغافورة', '+65'),
  CountryCode('🇹🇭', 'تايلاند', '+66'),
  CountryCode('🇻🇳', 'فيتنام', '+84'),
  CountryCode('🇮🇷', 'إيران', '+98'),
  CountryCode('🇦🇫', 'أفغانستان', '+93'),
  CountryCode('🇧🇷', 'البرازيل', '+55'),
  CountryCode('🇲🇽', 'المكسيك', '+52'),
  CountryCode('🇦🇷', 'الأرجنتين', '+54'),
  CountryCode('🇨🇴', 'كولومبيا', '+57'),
  CountryCode('🇨🇱', 'تشيلي', '+56'),
  CountryCode('🇵🇪', 'بيرو', '+51'),
  CountryCode('🇿🇦', 'جنوب أفريقيا', '+27'),
  CountryCode('🇳🇬', 'نيجيريا', '+234'),
  CountryCode('🇰🇪', 'كينيا', '+254'),
  CountryCode('🇬🇭', 'غانا', '+233'),
  CountryCode('🇪🇹', 'إثيوبيا', '+251'),
  CountryCode('🇹🇿', 'تنزانيا', '+255'),
  CountryCode('🇺🇬', 'أوغندا', '+256'),
  CountryCode('🇷🇼', 'رواندا', '+250'),
  CountryCode('🇿🇼', 'زيمبابوي', '+263'),
  CountryCode('🇿🇲', 'زامبيا', '+260'),
  CountryCode('🇨🇲', 'الكاميرون', '+237'),
  CountryCode('🇸🇳', 'السنغال', '+221'),
  CountryCode('🇨🇮', 'ساحل العاج', '+225'),
  CountryCode('🇲🇱', 'مالي', '+223'),
  CountryCode('🇧🇫', 'بوركينا فاسو', '+226'),
  CountryCode('🇳🇪', 'النيجر', '+227'),
  CountryCode('🇹🇩', 'تشاد', '+235'),
  CountryCode('🇨🇬', 'الكونغو', '+242'),
  CountryCode('🇨🇩', 'الكونغو الديمقراطية', '+243'),
  CountryCode('🇦🇴', 'أنغولا', '+244'),
  CountryCode('🇲🇿', 'موزمبيق', '+258'),
  CountryCode('🇲🇬', 'مدغشقر', '+261'),
  CountryCode('🇲🇼', 'ملاوي', '+265'),
  CountryCode('🇧🇼', 'بوتسوانا', '+267'),
  CountryCode('🇳🇦', 'ناميبيا', '+264'),
  CountryCode('🇲🇺', 'موريشيوس', '+230'),
  CountryCode('🇲🇷', 'موريتانيا', '+222'),
  CountryCode('🇩🇯', 'جيبوتي', '+253'),
  CountryCode('🇪🇷', 'إريتريا', '+291'),
  CountryCode('🇸🇸', 'جنوب السودان', '+211'),
  CountryCode('🇨🇫', 'أفريقيا الوسطى', '+236'),
  CountryCode('🇬🇶', 'غينيا الاستوائية', '+240'),
  CountryCode('🇬🇦', 'الغابون', '+241'),
  CountryCode('🇸🇹', 'ساو تومي', '+239'),
  CountryCode('🇨🇻', 'الرأس الأخضر', '+238'),
  CountryCode('🇬🇲', 'غامبيا', '+220'),
  CountryCode('🇬🇼', 'غينيا بيساو', '+245'),
  CountryCode('🇬🇳', 'غينيا', '+224'),
  CountryCode('🇸🇱', 'سيراليون', '+232'),
  CountryCode('🇱🇷', 'ليبيريا', '+231'),
  CountryCode('🇹🇬', 'توغو', '+228'),
  CountryCode('🇧🇯', 'بنين', '+229'),
  CountryCode('🇱🇸', 'ليسوتو', '+266'),
  CountryCode('🇸🇿', 'إسواتيني', '+268'),
  CountryCode('🇰🇲', 'جزر القمر', '+269'),
  CountryCode('🇸🇨', 'سيشل', '+248'),
  CountryCode('🇧🇮', 'بوروندي', '+257'),
  CountryCode('🇷🇴', 'رومانيا', '+40'),
  CountryCode('🇭🇺', 'المجر', '+36'),
  CountryCode('🇨🇿', 'التشيك', '+420'),
  CountryCode('🇸🇰', 'سلوفاكيا', '+421'),
  CountryCode('🇸🇮', 'سلوفينيا', '+386'),
  CountryCode('🇭🇷', 'كرواتيا', '+385'),
  CountryCode('🇧🇦', 'البوسنة والهرسك', '+387'),
  CountryCode('🇷🇸', 'صربيا', '+381'),
  CountryCode('🇲🇪', 'الجبل الأسود', '+382'),
  CountryCode('🇲🇰', 'مقدونيا الشمالية', '+389'),
  CountryCode('🇦🇱', 'ألبانيا', '+355'),
  CountryCode('🇧🇬', 'بلغاريا', '+359'),
  CountryCode('🇧🇾', 'بيلاروسيا', '+375'),
  CountryCode('🇲🇩', 'مولدوفا', '+373'),
  CountryCode('🇱🇹', 'ليتوانيا', '+370'),
  CountryCode('🇱🇻', 'لاتفيا', '+371'),
  CountryCode('🇪🇪', 'إستونيا', '+372'),
  CountryCode('🇮🇸', 'آيسلندا', '+354'),
  CountryCode('🇮🇪', 'آيرلندا', '+353'),
  CountryCode('🇱🇺', 'لوكسمبورغ', '+352'),
  CountryCode('🇲🇨', 'موناكو', '+377'),
  CountryCode('🇦🇩', 'أندورا', '+376'),
  CountryCode('🇱🇮', 'ليختنشتاين', '+423'),
  CountryCode('🇸🇲', 'سان مارينو', '+378'),
  CountryCode('🇻🇦', 'الفاتيكان', '+379'),
  CountryCode('🇨🇾', 'قبرص', '+357'),
  CountryCode('🇲🇹', 'مالطا', '+356'),
  CountryCode('🇽🇰', 'كوسوفو', '+383'),
  CountryCode('🇬🇪', 'جورجيا', '+995'),
  CountryCode('🇦🇲', 'أرمينيا', '+374'),
  CountryCode('🇦🇿', 'أذربيجان', '+994'),
  CountryCode('🇰🇿', 'كازاخستان', '+7'),
  CountryCode('🇺🇿', 'أوزبكستان', '+998'),
  CountryCode('🇹🇲', 'تركمانستان', '+993'),
  CountryCode('🇰🇬', 'قيرغيزستان', '+996'),
  CountryCode('🇹🇯', 'طاجيكستان', '+992'),
  CountryCode('🇲🇳', 'منغوليا', '+976'),
  CountryCode('🇳🇵', 'نيبال', '+977'),
  CountryCode('🇧🇹', 'بوتان', '+975'),
  CountryCode('🇱🇰', 'سريلانكا', '+94'),
  CountryCode('🇲🇻', 'المالديف', '+960'),
  CountryCode('🇲🇲', 'ميانمار', '+95'),
  CountryCode('🇰🇭', 'كمبوديا', '+855'),
  CountryCode('🇱🇦', 'لاوس', '+856'),
  CountryCode('🇹🇱', 'تيمور الشرقية', '+670'),
  CountryCode('🇧🇳', 'بروناي', '+673'),
  CountryCode('🇵🇬', 'بابوا غينيا الجديدة', '+675'),
  CountryCode('🇫🇯', 'فيجي', '+679'),
  CountryCode('🇸🇧', 'جزر سليمان', '+677'),
  CountryCode('🇻🇺', 'فانواتو', '+678'),
  CountryCode('🇼🇸', 'ساموا', '+685'),
  CountryCode('🇹🇴', 'تونغا', '+676'),
  CountryCode('🇰🇮', 'كيريباتي', '+686'),
  CountryCode('🇳🇷', 'ناورو', '+674'),
  CountryCode('🇵🇼', 'بالاو', '+680'),
  CountryCode('🇲🇭', 'جزر مارشال', '+692'),
  CountryCode('🇫🇲', 'ميكرونيزيا', '+691'),
  CountryCode('🇹🇻', 'توفالو', '+688'),
  CountryCode('🇨🇺', 'كوبا', '+53'),
  CountryCode('🇯🇲', 'جامايكا', '+1876'),
  CountryCode('🇭🇹', 'هايتي', '+509'),
  CountryCode('🇩🇴', 'الدومينيكان', '+1809'),
  CountryCode('🇵🇷', 'بورتوريكو', '+1787'),
  CountryCode('🇹🇹', 'ترينيداد وتوباغو', '+1868'),
  CountryCode('🇧🇧', 'باربادوس', '+1246'),
  CountryCode('🇱🇨', 'سانت لوسيا', '+1758'),
  CountryCode('🇻🇨', 'سانت فنسنت', '+1784'),
  CountryCode('🇬🇩', 'غرينادا', '+1473'),
  CountryCode('🇩🇲', 'دومينيكا', '+1767'),
  CountryCode('🇦🇬', 'أنتيغوا وباربودا', '+1268'),
  CountryCode('🇰🇳', 'سانت كيتس ونيفيس', '+1869'),
  CountryCode('🇧🇸', 'الباهاماس', '+1242'),
  CountryCode('🇬🇹', 'غواتيمالا', '+502'),
  CountryCode('🇸🇻', 'السلفادور', '+503'),
  CountryCode('🇭🇳', 'هندوراس', '+504'),
  CountryCode('🇳🇮', 'نيكاراغوا', '+505'),
  CountryCode('🇨🇷', 'كوستاريكا', '+506'),
  CountryCode('🇵🇦', 'بنما', '+507'),
  CountryCode('🇧🇿', 'بليز', '+501'),
  CountryCode('🇻🇪', 'فنزويلا', '+58'),
  CountryCode('🇪🇨', 'الإكوادور', '+593'),
  CountryCode('🇧🇴', 'بوليفيا', '+591'),
  CountryCode('🇵🇾', 'باراغواي', '+595'),
  CountryCode('🇺🇾', 'أوروغواي', '+598'),
  CountryCode('🇬🇾', 'غيانا', '+592'),
  CountryCode('🇸🇷', 'سورينام', '+597'),
  CountryCode('🇹🇼', 'تايوان', '+886'),
  CountryCode('🇭🇰', 'هونغ كونغ', '+852'),
  CountryCode('🇲🇴', 'ماكاو', '+853'),
  CountryCode('🇮🇱', 'إسرائيل', '+972'),
  CountryCode('🇰🇵', 'كوريا الشمالية', '+850'),
];
